"""Differential test: our recursive splitter against the reference implementation.

`chunking_lab.chunkers.recursive` is a port of ``RecursiveTokenChunker`` from
brandonstarxel/chunking_evaluation (MIT), rewritten to carry character ranges
rather than strings. The rewrite is the point -- ranges are what the metrics need
-- but it is also exactly the kind of change that silently alters where the cuts
land, and this tool's correctness proof is reproducing a *published* table
(README C17). A port that is merely reasonable is not good enough.

``golden_recursive.json`` holds the reference implementation's own output for 28
(document, size, overlap) combinations, generated by running it directly. Nothing
here imports it at test time; the fixture is the record of what it did.

This test earned its keep immediately: it caught that the reference keeps a
separator as the *prefix* of the following piece, where the first port had it as
a suffix. Both are lossless, so the invariant passed and every size in the first
sample agreed -- only the differential showed the difference.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest
from chunking_lab import check, from_spec
from data_tools_core.provenance import Provenance, UnitKind

GOLDEN = json.loads((Path(__file__).parent / "golden_recursive.json").read_text())


def _provenance(name: str, text: str) -> Provenance:
    return Provenance(
        source=Path(f"{name}.md"),
        sha256=hashlib.sha256(text.encode()).hexdigest(),
        unit_kind=UnitKind.DOCUMENT,
    )


@pytest.mark.parametrize("case", sorted(GOLDEN["chunks"]))
def test_our_spans_reproduce_the_reference_chunks(case):
    name, size, overlap = case.split("|")
    text = GOLDEN["documents"][name]
    spec = f"recursive:{size}" + (f"/{overlap}" if overlap != "0" else "")

    chunking = from_spec(spec).chunk(text, _provenance(name, text))
    check(chunking, text)

    ours = [text[span.start : span.end] for span in chunking.spans]
    assert ours == GOLDEN["chunks"][case]


def test_the_fixture_covers_the_cases_that_distinguish_implementations():
    """A differential test is only worth its fixture."""
    cases = GOLDEN["chunks"]
    assert len(cases) >= 28
    # overlap on and off
    assert any(c.endswith("|0") for c in cases) and any(not c.endswith("|0") for c in cases)
    # a document with no separator at all, which forces the terminal split
    assert any(c.startswith("runon|") for c in cases)
    # a size small enough to force recursion past the first separator
    assert any("|40|" in c for c in cases)
    # a size larger than every document, which must yield exactly one chunk
    assert all(len(v) == 1 for k, v in cases.items() if "|10000|" in k)
